# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: rikorose/gcc-cmake:latest

before_script:
  - apt update && apt -y install make git

build:
  stage: build
  script:
    - cd build; cmake ..; make
    - ./examples/test4_2
    - make test
  stage: test
  script:
    - make test
    - ./examples/test4_2
