image: antalbuss/cpp20-cmake:latest

before_script:
  - apt update && apt -y install make git

stages:
  - build
  - test

build:
  stage: build
  artifacts:
   paths:
    - build/test/test1
    - build/test/test2
    - build/test/test3
    - build/examples/* 
  script:
    - cd build; cmake .. -DCMAKE_CXX_COMPILER=g++-10; make

test:
  stage: test
  artifacts:
   paths:
    - build/test/test1
    - build/test/test2
    - build/test/test3
    - build/examples/* 
  script:
    - build/test/test1
    - build/test/test2
    - build/test/test3
    - build/examples/example5
