image: antalbuss/cpp20-cmake:latest

before_script:
  - apt update && apt -y install make git

stages:
  - build
  - test

build:
  stage: build
  artifacts:
   paths:
    - build/test/test_1
    - build/test/test_2
    - build/examples/* 
  script:
    - cd build; cmake ..; make

test:
  stage: test
  artifacts:
   paths:
    - build/test/test_1
    - build/test/test_2
    - build/examples/* 
  script:
    - build/test/test_1
    - build/test/test_2
    - build/examples/example5
